/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jingju_jnitest_Test */

#ifndef _Included_com_jingju_jnitest_Test
#define _Included_com_jingju_jnitest_Test
#ifdef __cplusplus
extern "C" {
#endif
#include <malloc.h>
#include "common_tools.h"
#define LOG_TAG "test"


/*
 * Class:     com_jingju_jnitest_Test
 * Method:    testVoid
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jingju_jnitest_Test_testVoid
  (JNIEnv * env, jobject obj){

}

/*
 * Class:     com_jingju_jnitest_Test
 * Method:    testString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jingju_jnitest_Test_testString
  (JNIEnv *env, jobject obj){
    /* bug 开始*/
    env=0;
    /* bug 结束*/
    jstring str = env->NewStringUTF("1234");


    return str;
}

#ifdef __cplusplus
}
#endif
#endif
