/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jingju_jnitest_AVIPlayer */

#ifndef _Included_com_jingju_jnitest_AVIPlayer
#define _Included_com_jingju_jnitest_AVIPlayer
#ifdef __cplusplus
extern "C" {
#endif

#include <Common.h>

/*
 * Class:     com_jingju_jnitest_AVIPlayer
 * Method:    open
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_jingju_jnitest_AVIPlayer_open
  (JNIEnv *env, jclass clazz, jstring fileName){

}

/*
 * Class:     com_jingju_jnitest_AVIPlayer
 * Method:    getWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_jingju_jnitest_AVIPlayer_getWidth
  (JNIEnv *env, jclass clazz, jlong avi){

}

/*
 * Class:     com_jingju_jnitest_AVIPlayer
 * Method:    getHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_jingju_jnitest_AVIPlayer_getHeight
  (JNIEnv *env, jclass clzz, jlong avi){

}

/*
 * Class:     com_jingju_jnitest_AVIPlayer
 * Method:    getFrameRate
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_jingju_jnitest_AVIPlayer_getFrameRate
  (JNIEnv *env, jclass clazz, jlong avi){


}

/*
 * Class:     com_jingju_jnitest_AVIPlayer
 * Method:    close
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_jingju_jnitest_AVIPlayer_close
  (JNIEnv *env, jclass clazz, jlong avi){

}

#ifdef __cplusplus
}
#endif
#endif
